### get followers of a user
GET http://localhost:3000/followers/60aaa00fe7766449f7526693
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGFhYTAwNGU3NzY2NDQ5Zjc1MjY2OTIiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyMTc5NTI1OSwiZXhwIjoxNjIyMDk1MjU5fQ.DYVoOU0wYhkQbHgl4c6w5RT_oBcs0R-sarMt0oOG4jk


### get all the users our user is following
GET http://localhost:3000/followers/following/60aaa004e7766449f7526692
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGFhYTAwNGU3NzY2NDQ5Zjc1MjY2OTIiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyMTc5NTI1OSwiZXhwIjoxNjIyMDk1MjU5fQ.DYVoOU0wYhkQbHgl4c6w5RT_oBcs0R-sarMt0oOG4jk


### follow annother user
POST http://localhost:3000/followers/60aaa00fe7766449f7526693
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGFhYTAwNGU3NzY2NDQ5Zjc1MjY2OTIiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyMTc5NTI1OSwiZXhwIjoxNjIyMDk1MjU5fQ.DYVoOU0wYhkQbHgl4c6w5RT_oBcs0R-sarMt0oOG4jk


### stop following annother user
DELETE  http://localhost:3000/followers/60a7f35ed715f058ab15be89
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGFhYTAwNGU3NzY2NDQ5Zjc1MjY2OTIiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyMTc5NTI1OSwiZXhwIjoxNjIyMDk1MjU5fQ.DYVoOU0wYhkQbHgl4c6w5RT_oBcs0R-sarMt0oOG4jk

# user:
# 60aaa00fe7766449f7526693
# admin:
# 60aaa004e7766449f7526692