### Create User
POST http://localhost:3000/users
content-type: application/json

{
  "username": "malte5",
  "password": "testPassword",
  "email": "hello5@malts.me"
}

### Get Users
GET http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGFhYTAwNGU3NzY2NDQ5Zjc1MjY2OTIiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyMjA3NDE3OSwiZXhwIjoxNjIyMzc0MTc5fQ.B23DFXE13QOgBvPUC2BKqKsVIYswmpbEG5s7q0XW1t0

### Verify Email ( token printed in server log )
PATCH http://localhost:3000/users/
content-type: application/json

{
  "emailVerificationToken": "ThZErSxeXntiafLCGA3r"
}


### Change password
PATCH http://localhost:3000/users/:userId
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDdjYTU1NjUxZTA5YzI1N2M1NWU3ODIiLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAZGVtby5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjE4NzgxNTI2LCJleHAiOjE2MTkwODE1MjZ9.Lg1qwIilkKxQvSCLMrrsUkirq9-WHINiKIHrcdGPVKE
content-type: application/json

{
  "password": "testPassword"
}


### Delete User
DELETE http://localhost:3000/users/60aee1a560f0ae3b1abec4b0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGFlZTRiM2NmZWVmMDNlYWJhMjg5NmQiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyMjA3NDU0NywiZXhwIjoxNjIyMzc0NTQ3fQ.CRRBFthhmaDj0pY-MM2zXts8rlVLh7OcvEJjsApM-xY

