### Create User
POST http://localhost:3000/users
content-type: application/json

{
  "username": "test",
  "password": "testPassword",
  "email": "test@demo.com"
}

### Get Users
GET http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDk5OTE2ZWI2NTY4YjM5N2QwNTUyODkiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyMTYxOTMxNSwiZXhwIjoxNjIxOTE5MzE1fQ.tlhaHU9rWYr4w31apB5YHHpe-OXYkK2kwASZ8bbVOg8

### Verify Email ( token printed in server log )
PATCH http://localhost:3000/users/
content-type: application/json

{
  "emailVerificationToken": "ThZErSxeXntiafLCGA3r"
}


### Change password
PATCH http://localhost:3000/users/:userId
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDdjYTU1NjUxZTA5YzI1N2M1NWU3ODIiLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAZGVtby5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjE4NzgxNTI2LCJleHAiOjE2MTkwODE1MjZ9.Lg1qwIilkKxQvSCLMrrsUkirq9-WHINiKIHrcdGPVKE
content-type: application/json

{
  "password": "testPassword"
}


### Delete User
DELETE http://localhost:3000/users/607df374d11842e77fa72e50
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDdkZjM3NGQxMTg0MmU3N2ZhNzJlNTAiLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAZGVtby5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjE4ODY3MDYwLCJleHAiOjE2MTkxNjcwNjB9.6ig482lMkS4nOuG24C1m33y6NlSxUs_kDZwju43yCnU

