###
POST http://localhost:3000/images/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDk0NDg4YjkzYThhNTM0ZGM2YThkYmEiLCJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyMDMzMDYzNSwiZXhwIjoxNjIwNjMwNjM1fQ.dxoCY0h2_LDqJIJq9tRT2UjIJy5FNnbbgCs7G_NuuiI
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="example.jpg"
Content-Type: image/jpeg

< ./../../../test/example.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 
GET http://localhost:3000/images/6094489b93a8a534dc6a8dbb
Content-Type: application/json
###
GET http://localhost:3000/images/
Content-Type: application/json